import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "@/vendor/css/nes.css";
import "./globals.css";
import { BackgroundMusic } from "@/components/background-music";

const pressStart2P = Press_Start_2P({
  weight: "400",
  variable: "--font-press-start-2p",
  subsets: ["latin"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pressStart2P.variable} antialiased bg-sky !bg-cover animate-bg font-[var(--font-press-start-2p)]`}
      >
        <div className="flex flex-row-reverse items-center gap-6 px-6 md:absolute w-full justify-center md:justify-start">
          <a
            href="https://github.com/thisisabhinay/connect-4"
            target="_blank"
            className="nes-icon github is-large"
          />
          <BackgroundMusic />
        </div>
        {children}
      </body>
    </html>
  );
}
