import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "@/vendor/css/nes.css";
import "./globals.css";

/**
 * Configures Press Start 2P font with specific metrics for pixel-perfect rendering
 * Sets weight to 400 (regular) and ensures proper spacing in retro-style UI
 * Maps font to CSS variable for consistent usage across components
 * Only loads Latin character subset to optimize bundle size
 */
const pressStart2P = Press_Start_2P({
  weight: "400",
  variable: "--font-press-start-2p",
  subsets: ["latin"],
  style: "normal",
});

/**
 * Core metadata configuration for SEO and social sharing
 * Sets base title and description for all pages that don't override
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout wrapper that provides consistent styling across all pages
 * Applies Press Start 2P font through CSS variable system
 * Enables font smoothing via antialiased class
 * Forces full height rendering to prevent layout shifts
 *
 * @param children - Next.js pages/components to be wrapped by this layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pressStart2P.variable} antialiased  h-full`}>
        {children}
      </body>
    </html>
  );
}
